spring:
  application:
    name: app-eureka-registry
  profiles:    active:    -  ${PROFILE:dev}
server:  port: 9191
eureka:  client:    service-url:       defaultZone: http://${EUREKA_HOST:localhost}:9191/eureka/    fetch-registry: false    register-with-eureka: false
logging:  pattern:    level: debug